# the version of the docker-compose
version: '3.8'

services:

  mariadb:
    build: ./mariadb
    container_name: mariadb
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - mdb_vol:/var/lib/mysql
    networks:
      - inception
    restart: on-failure

  wordpress:
    build: ./wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    env_file: .env
    ports:
      - "9000:9000"
    volumes:
      - wp_vol:/var/www/html
    networks:
      - inception
    restart: on-failure

  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
      - wordpress
    env_file: .env
    ports:
      - "443:443"
    volumes:
      - wp_vol:/var/www/html
    networks:
      - inception
    restart: on-failure

networks:
  inception:
    driver: bridge

volumes:
  mdb_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/ddyankov/data/mdb_vol
      o: bind
  
  wp_vol:
    driver: local
    driver_opts:
#is a simple bind mount, where vol is directly mounted from a host path
      type: none 
      device: /home/ddyankov/data/wp_vol
#Allows the container to directly access the files from the host path.
      o: bind
    
