# the version of the docker-compose
version: '3.8'

services:

  mariadb:
    build: ./mariadb
    container_name: mariadb
    env_file: .env
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - inception
    restart: on-failure

  wordpress:
    build: ./services/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    env_file: .env
    ports:
      - "127.0.0.1:9000:9000"
    volumes:
      -wordpress:/var/www/html
    networks:
      - inception
    restart: on-failure

    nginx:
      build: ./services/nginx
      container_name: nginx
      depends_on:
        - wordpress
      env_file: .env
      ports:
        - "443:443"
      volumes:
        - wordpress_volume:/var/www/html
      networks:
        - inception
      restart: on-failure

networks:
  inception:
    driver: bridge

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/mariadb_volume
      o: bind
  
  wordpress_volume:
    driver: local
    driver_opts:
#is a simple bind mount, where vol is directly mounted from a host path
      type: none 
      device: /home/${USER}/data/wordpress_volume
#Allows the container to directly access the files from the host path.
      o: bind
    
